version: '3.8'

services:
  backend:
    build: .
    container_name: web-scraping-api

    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/scraping_db
      DB_USERNAME: admin
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
  db:
    ports:
      - "5432:5432"
    container_name: postgres_scraping
    image: postgres:alpine
    environment:
      - POSTGRES_DB=scraping_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
